/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Jeshuan
 */
public class FrmBarraInferior extends javax.swing.JInternalFrame {
private Timer timer;
private int indiceImagen = 0;
    /**
     * Creates new form FrmBarraInferior
     */
    public FrmBarraInferior() {
        initComponents();
         ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
         iniciarTimer(imagenesSUV, textosSUV);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTextos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbOpcion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(578, 377));
        jLayeredPane1.add(lblImagen);
        lblImagen.setBounds(170, 80, 260, 190);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Auto destacado");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(10, 10, 190, 32);

        lblTextos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTextos.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.add(lblTextos);
        lblTextos.setBounds(20, 50, 170, 20);
        jLayeredPane1.add(jSeparator1);
        jSeparator1.setBounds(10, 40, 180, 10);

        cmbOpcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUV", "Pick-Up", "Sedan" }));
        cmbOpcion.setFocusCycleRoot(true);
        cmbOpcion.setOpaque(true);
        cmbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpcionActionPerformed(evt);
            }
        });
        jLayeredPane1.add(cmbOpcion);
        cmbOpcion.setBounds(480, 0, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo publicidad.png"))); // NOI18N
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(0, 0, 570, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private final ImageIcon[] imagenesSUV = {
    new ImageIcon(getClass().getResource("/imagenes/ToyotaSuvAzul.png")),
    new ImageIcon(getClass().getResource("/imagenes/NissanSuvRoja.png")),
    new ImageIcon(getClass().getResource("/imagenes/BmwSuvNegra.png")),
};
    private final ImageIcon[] imagenesPickUp = {
    new ImageIcon(getClass().getResource("/imagenes/ToyotaHiluxBlanca.png")),
    new ImageIcon(getClass().getResource("/imagenes/ChevroletSilveradoGris.png")),
    new ImageIcon(getClass().getResource("/imagenes/FordRangerCeleste.png")),
};
     private final ImageIcon[] imagenesSedan = {
    new ImageIcon(getClass().getResource("/imagenes/BmwM6Azul.png")),
    new ImageIcon(getClass().getResource("/imagenes/ChevroletOnixAzul.png")),
    new ImageIcon(getClass().getResource("/imagenes/AudiA6Negro.png")),
};
private final String[] textosSUV = {
    "Toyota RAV4 2016",
    "Nissan Kicks 2020",
    "Bmw X6 2024"
};
private final String[] textosSedan = {
    "BMW M6 2020",
    "Chevrolet Onix 2018",
    "Audi A6 2022"
};
private final String[] textosPickUp = {
    "Toyota Hilux 2022",
    "Chevrolet Silverado 2024",
    "Ford Ranger 2024"
};
    private void cmbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionActionPerformed
      String seleccion = (String) cmbOpcion.getSelectedItem();
            
            // Lógica para cambiar de timer según la selección
            switch (seleccion) {
                case "SUV":
                    iniciarTimer(imagenesSUV, textosSUV);
                    break;
                case "Pick-Up":
                    iniciarTimer(imagenesPickUp, textosPickUp);
                    break;
                case "Sedan":
                    iniciarTimer(imagenesSedan, textosSedan);
                    break;
            }
            
    }
    private void iniciarTimer(ImageIcon[] imagenes, String[] textos) {
    if (timer != null && timer.isRunning()) {
        timer.stop();
    }
    
    indiceImagen = 0;
    
    if (imagenes.length > 0) {
        lblImagen.setIcon(imagenes[indiceImagen]);
        lblTextos.setText(textos[indiceImagen]);
    }

    // Creamos un nuevo Timer que se dispara cada 3 segundos
    timer = new Timer(3000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            indiceImagen = (indiceImagen + 1) % imagenes.length;
            
           
            lblImagen.setIcon(imagenes[indiceImagen]);
            lblTextos.setText(textos[indiceImagen]);
        }
    });
    
    timer.start(); // Iniciar temporizador
    }//GEN-LAST:event_cmbOpcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTextos;
    // End of variables declaration//GEN-END:variables
}
