/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import GUI.Principal;
/**
 *
 * @author Jeshuan
 */
public class FrmBarraBotones extends javax.swing.JInternalFrame {
private Principal main;
    /**
     * Creates new form FrmBarraBotones
     */
    public FrmBarraBotones(Principal main) {
        initComponents();
         ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
         this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVehiculo = new javax.swing.JButton();
        btnVehiculo2 = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVehiculo1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnReserva = new javax.swing.JButton();
        btnVehiculo6 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        btnVehiculo.setBackground(new java.awt.Color(204, 204, 204));
        btnVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/car (2).png"))); // NOI18N
        btnVehiculo.setText("Vehiculos");
        btnVehiculo.setBorder(null);
        btnVehiculo.setBorderPainted(false);
        btnVehiculo.setContentAreaFilled(false);

        btnVehiculo2.setBackground(new java.awt.Color(204, 204, 204));
        btnVehiculo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/car (2).png"))); // NOI18N
        btnVehiculo2.setText("Vehiculos");
        btnVehiculo2.setBorder(null);
        btnVehiculo2.setBorderPainted(false);
        btnVehiculo2.setContentAreaFilled(false);
        btnVehiculo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculo2ActionPerformed(evt);
            }
        });

        setBorder(null);

        btnClientes.setBackground(new java.awt.Color(204, 204, 204));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnClientes.setText("Cliente");
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnVehiculo1.setBackground(new java.awt.Color(204, 204, 204));
        btnVehiculo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/car (2).png"))); // NOI18N
        btnVehiculo1.setText("Vehiculos");
        btnVehiculo1.setBorder(null);
        btnVehiculo1.setBorderPainted(false);
        btnVehiculo1.setContentAreaFilled(false);
        btnVehiculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculo1ActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/owner.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorder(null);
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnReserva.setBackground(new java.awt.Color(204, 204, 204));
        btnReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservation.png"))); // NOI18N
        btnReserva.setText("Reservas");
        btnReserva.setBorder(null);
        btnReserva.setBorderPainted(false);
        btnReserva.setContentAreaFilled(false);
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        btnVehiculo6.setBackground(new java.awt.Color(204, 204, 204));
        btnVehiculo6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contract (1).png"))); // NOI18N
        btnVehiculo6.setText("Contratos");
        btnVehiculo6.setBorder(null);
        btnVehiculo6.setBorderPainted(false);
        btnVehiculo6.setContentAreaFilled(false);
        btnVehiculo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculo6ActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnVehiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnVehiculo6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVehiculo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVehiculo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehiculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculo1ActionPerformed
        main.mostrarVehiculo();
    }//GEN-LAST:event_btnVehiculo1ActionPerformed

    private void btnVehiculo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculo2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        main.mostrarEmpleado();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
       main.mostrarReserva();
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnVehiculo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculo6ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
     main.mostrarHome();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        main.mostrarCliente();
        
    }//GEN-LAST:event_btnClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReserva;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVehiculo;
    private javax.swing.JButton btnVehiculo1;
    private javax.swing.JButton btnVehiculo2;
    private javax.swing.JButton btnVehiculo6;
    // End of variables declaration//GEN-END:variables
}
