/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Gestion_Listas.*;
import Gestion_Personas.Cliente;
import Gestion_Vehiculo.Vehiculo;
import Gestion_Reservas.Reservas;
import Gestion_Vehiculo.TipoVehiculo;
import Util.UtilGui;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
/**
 *
 * @author Joan
 */
public class FrmReservas extends javax.swing.JInternalFrame {
 private ListaReservas listaReservas;
    private ListaClientes listaClientes;
    private ListaVehiculos listaVehiculos;
    /**
     * Creates new form FrmReservas
     */
     public void setList(ListaReservas listaReservas){
        this.listaReservas = listaReservas;
    }      
     public FrmReservas(ListaReservas reservas, ListaClientes clientes, ListaVehiculos vehiculos) {
        this.listaReservas = reservas;
        this.listaClientes = clientes;
        this.listaVehiculos = vehiculos;
        
        initComponents();
       configurarComponentes();
        cargarDatos();
    }

     private void configurarComponentes() {
          tablaReservas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarDatosReservaSeleccionada();
            }
        });
    }
    
    private void cargarDatos() {
        cargarClientes();
        cargarTiposVehiculo();
        cargarTablaReservas();
    }
    
    public void cargarClientes() {
     cmbClientes.removeAllItems();
        cmbClientes.addItem("Seleccione cliente...");
        
        for (Cliente c : listaClientes.obtenerTodos()) {
            cmbClientes.addItem(c.getCedula() + " - " + c.getNombre());
        }
    }
    
    private void cargarTiposVehiculo() {
      cmbTipoVehiculo.removeAllItems();
    cmbTipoVehiculo.addItem("Seleccione tipo...");
    
    for (TipoVehiculo tipo : TipoVehiculo.values()) {
        cmbTipoVehiculo.addItem(tipo.getDescripcion());
    }
    }
    
    private void cargarTablaReservas() {
          DefaultTableModel modelo = (DefaultTableModel) tablaReservas.getModel();
        modelo.setRowCount(0);
        for (Reservas r : listaReservas.getReservasActivas()) {
            String vehiculoInfo = r.getVehiculo() != null ? 
                r.getVehiculo().getPlaca() + " - " + r.getVehiculo().getMarca() : 
                "Sin asignar";
                
            Object[] fila = {
                r.getCliente().getNombre(),
                vehiculoInfo,
                r.getFechaInicioAlquiler().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                r.getFechaFinAlquiler().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                "Activa"
            };
            modelo.addRow(fila);
        }
        
       
        for (Reservas r : listaReservas.getReservasEspera()) {
            Object[] fila = {
                r.getCliente().getNombre(),
                "En espera",
                r.getFechaInicioAlquiler().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                r.getFechaFinAlquiler().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                "En Espera"
            };
            modelo.addRow(fila);
        }
    }
     private void cargarDatosReservaSeleccionada() {
    int filaSeleccionada = tablaReservas.getSelectedRow();
        if (filaSeleccionada >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tablaReservas.getModel();
            
            String nombreCliente = (String) modelo.getValueAt(filaSeleccionada, 0);
            String fechaInicio = (String) modelo.getValueAt(filaSeleccionada, 2);
            String fechaFin = (String) modelo.getValueAt(filaSeleccionada, 3);
            
        
            for (int i = 0; i < cmbClientes.getItemCount(); i++) {
                String itemCombo = (String) cmbClientes.getItemAt(i);
                if (itemCombo.contains(nombreCliente)) {
                    cmbClientes.setSelectedIndex(i);
                    break;
                }
            }
           
            txtFechaInicio.setText(fechaInicio);
            txtFechaFin.setText(fechaFin);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        cmbTipoVehiculo = new javax.swing.JComboBox<>();
        btnCrearReserva = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnBuscarPorCliente = new javax.swing.JButton();
        btnBuscarPorFechas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionar Reservas ");

        tablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Vehiculo", "Fecha de inicio", "Estado", "Fecha Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaReservas);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Buscar");

        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmar)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnRefrescar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tipo Vehiculo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("F. Inicio:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nueva Reserva");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("F. Fin:");

        btnCrearReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCrearReserva.setText("Crear Reserva");
        btnCrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(137, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(105, 105, 105))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(55, 55, 55)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnCrearReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BUSQUEDAS");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Buscar:");

        btnBuscarPorCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarPorCliente.setText("\"Por Clientes\"");
        btnBuscarPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorClienteActionPerformed(evt);
            }
        });

        btnBuscarPorFechas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarPorFechas.setText("\"Por Fecha\"");
        btnBuscarPorFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorFechasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarPorCliente)
                        .addGap(38, 38, 38)))
                .addComponent(btnBuscarPorFechas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorCliente)
                    .addComponent(btnBuscarPorFechas))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearReservaActionPerformed
          try {
        if (!validarCampos()) return;
        
        Cliente cliente = obtenerClienteSeleccionado();
        
       
        String descripcionSeleccionada = (String) cmbTipoVehiculo.getSelectedItem();
        TipoVehiculo tipoSeleccionado = obtenerTipoPorDescripcion(descripcionSeleccionada);
        
        LocalDate fechaInicio = LocalDate.parse(txtFechaInicio.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate fechaFin = LocalDate.parse(txtFechaFin.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        
        boolean resultado = listaReservas.crearReservaPorTipo(cliente, tipoSeleccionado, fechaInicio, fechaFin);
        
        if (resultado) {
            UtilGui.showMessage(this, "Reserva creada y vehículo asignado", "Éxito");
        } else {
            UtilGui.showMessage(this, "No hay vehículos disponibles. Reserva en lista de espera.", "En Espera");
        }
        
        cargarDatos();
        limpiarFormulario();
        
    } catch (DateTimeParseException e) {
        UtilGui.showErrorMessage(this, "Formato de fecha incorrecto. Use dd/MM/yyyy", "Error");
    } catch (Exception e) {
        UtilGui.showErrorMessage(this, "Error al crear reserva: " + e.getMessage(), "Error");
    }
    }//GEN-LAST:event_btnCrearReservaActionPerformed

    private void btnBuscarPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorClienteActionPerformed
        String busqueda = jTextField1.getText().trim();
        if (busqueda.isEmpty()) {
            UtilGui.showErrorMessage(this, "Ingrese cédula del cliente", "Error");
            return;
        }
        
        ArrayList<Reservas> resultados = listaReservas.buscarPorCliente(busqueda);
        mostrarResultadosBusqueda(resultados);
    }//GEN-LAST:event_btnBuscarPorClienteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         int filaSeleccionada = tablaReservas.getSelectedRow();
        if (filaSeleccionada < 0) {
            UtilGui.showErrorMessage(this, "Seleccione una reserva", "Error");
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tablaReservas.getModel();
        String estado = (String) modelo.getValueAt(filaSeleccionada, 4);
        
        if (!estado.equals("Activa")) {
            UtilGui.showErrorMessage(this, "Solo se pueden modificar reservas activas", "Error");
            return;
        }
        
        String[] opciones = {"Sedán", "SUV", "Pick-up"};
        String tipoStr = (String) JOptionPane.showInputDialog(this,
            "Seleccione nuevo tipo de vehículo:",
            "Modificar Reserva",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            "Sedán");
        
        if (tipoStr != null) {
            TipoVehiculo nuevoTipo = obtenerTipoPorDescripcion(tipoStr);
            Reservas reservaSeleccionada = buscarReservaPorFila(filaSeleccionada);
            if (reservaSeleccionada != null) {
                if (listaReservas.modificarVehiculo(reservaSeleccionada, nuevoTipo)) {
                    UtilGui.showMessage(this, "Reserva modificada exitosamente", "Éxito");
                    cargarTablaReservas();
                } else {
                    UtilGui.showErrorMessage(this, "No hay vehículos disponibles del tipo seleccionado", "Error");
                }
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          int filaSeleccionada = tablaReservas.getSelectedRow();
        if (filaSeleccionada < 0) {
            UtilGui.showErrorMessage(this, "Seleccione una reserva para cancelar", "Error");
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de cancelar esta reserva?", 
            "Confirmar cancelación", 
            JOptionPane.YES_NO_OPTION);
            
        if (confirmacion == JOptionPane.YES_OPTION) {
            Reservas reservaAEliminar = buscarReservaPorFila(filaSeleccionada);
            
            if (reservaAEliminar != null && listaReservas.eliminar(reservaAEliminar)) {
                UtilGui.showMessage(this, "Reserva cancelada exitosamente", "Información");
                cargarTablaReservas();
            } else {
                UtilGui.showErrorMessage(this, "No se pudo cancelar la reserva", "Error");
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        int filaSeleccionada = tablaReservas.getSelectedRow();
        if (filaSeleccionada < 0) {
            UtilGui.showErrorMessage(this, "Seleccione una reserva", "Error");
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tablaReservas.getModel();
        String estado = (String) modelo.getValueAt(filaSeleccionada, 4);
        
        if (!estado.equals("En Espera")) {
            UtilGui.showErrorMessage(this, "Solo se pueden confirmar reservas en espera", "Error");
            return;
        }
        
       
        listaReservas.procesarReservasEspera();
        cargarTablaReservas();
        UtilGui.showMessage(this, "Cola de espera procesada", "Información");
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnBuscarPorFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorFechasActionPerformed
      try {
            String fechaStr = jTextField1.getText().trim();
            if (fechaStr.isEmpty()) {
                UtilGui.showErrorMessage(this, "Ingrese una fecha (dd/MM/yyyy)", "Error");
                return;
            }
            
            LocalDate fecha = LocalDate.parse(fechaStr, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            ArrayList<Reservas> resultados = listaReservas.buscarPorFechas(fecha, fecha.plusDays(1));
            mostrarResultadosBusqueda(resultados);
            
        } catch (DateTimeParseException e) {
            UtilGui.showErrorMessage(this, "Formato de fecha incorrecto. Use dd/MM/yyyy", "Error");
        }
    }//GEN-LAST:event_btnBuscarPorFechasActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarDatos(); 
    UtilGui.showMessage(this, "Datos actualizados", "Información");
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
      
private boolean validarCampos() {
        if (cmbClientes.getSelectedIndex() == 0) {
            UtilGui.showErrorMessage(this, "Seleccione un cliente", "Error");
            return false;
        }
        
        if (cmbTipoVehiculo.getSelectedIndex() == 0) {
            UtilGui.showErrorMessage(this, "Seleccione un tipo de vehículo", "Error");
            return false;
        }
        
        if (!UtilGui.validateRequiere(txtFechaInicio, txtFechaFin)) {
            UtilGui.showErrorMessage(this, "Complete todas las fechas", "Error");
            return false;
        }
        
        try {
            LocalDate fechaInicio = LocalDate.parse(txtFechaInicio.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            LocalDate fechaFin = LocalDate.parse(txtFechaFin.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            
            if (fechaInicio.isBefore(LocalDate.now())) {
                UtilGui.showErrorMessage(this, "La fecha de inicio no puede ser anterior a hoy", "Error");
                return false;
            }
            
            if (!fechaFin.isAfter(fechaInicio)) {
                UtilGui.showErrorMessage(this, "La fecha de fin debe ser posterior a la de inicio", "Error");
                return false;
            }
            
            if (fechaInicio.until(fechaFin).getDays() > 30) {
                UtilGui.showErrorMessage(this, "No se permiten reservas de más de 30 días", "Error");
                return false;
            }
            
        } catch (DateTimeParseException e) {
            UtilGui.showErrorMessage(this, "Formato de fecha incorrecto. Use dd/MM/yyyy", "Error");
            return false;
        }
        
        return true;
    }
     private Cliente obtenerClienteSeleccionado() {
          String seleccion = (String) cmbClientes.getSelectedItem();
        String cedula = seleccion.split(" - ")[0];
        return listaClientes.buscar(cedula);
    }
    
    private Vehiculo obtenerVehiculoSeleccionado() {
        String seleccion = (String) cmbTipoVehiculo.getSelectedItem();
        String placa = seleccion.split(" - ")[0];
        return listaVehiculos.buscar(placa);
    }
    
    private void limpiarFormulario() {
         cmbClientes.setSelectedIndex(0);
        cmbTipoVehiculo.setSelectedIndex(0);
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
    }
 private Reservas buscarReservaPorFila(int fila) {
        DefaultTableModel modelo = (DefaultTableModel) tablaReservas.getModel();
        String nombreCliente = (String) modelo.getValueAt(fila, 0);
        String estado = (String) modelo.getValueAt(fila, 4);
        String fechaInicio = (String) modelo.getValueAt(fila, 2);
        
        LocalDate fecha = LocalDate.parse(fechaInicio, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        
        if (estado.equals("Activa")) {
            for (Reservas r : listaReservas.getReservasActivas()) {
                if (r.getCliente().getNombre().equals(nombreCliente) &&
                    r.getFechaInicioAlquiler().equals(fecha)) {
                    return r;
                }
            }
        } else {
            for (Reservas r : listaReservas.getReservasEspera()) {
                if (r.getCliente().getNombre().equals(nombreCliente) &&
                    r.getFechaInicioAlquiler().equals(fecha)) {
                    return r;
                }
            }
        }
        return null;
 }
    private void mostrarResultadosBusqueda(ArrayList<Reservas> resultados) {
        DefaultTableModel modelo = (DefaultTableModel) tablaReservas.getModel();
        modelo.setRowCount(0);
        
        if (resultados.isEmpty()) {
            UtilGui.showMessage(this, "No se encontraron reservas", "Información");
            cargarTablaReservas();
            return;
        }
        
        for (Reservas r : resultados) {
            String vehiculoInfo = r.getVehiculo() != null ? 
                r.getVehiculo().getPlaca() + " - " + r.getVehiculo().getMarca() : 
                "Sin asignar";
                
            Object[] fila = {
                r.getCliente().getNombre(),
                vehiculoInfo,
                r.getFechaInicioAlquiler().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                r.getFechaFinAlquiler().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                r.getVehiculo() != null ? "Activa" : "En Espera"
            };
            modelo.addRow(fila);
        }
        
        UtilGui.showMessage(this, "Se encontraron " + resultados.size() + " reservas", "Resultados");
    }
    private TipoVehiculo obtenerTipoPorDescripcion(String descripcion) {
        for (TipoVehiculo tipo : TipoVehiculo.values()) {
            if (tipo.getDescripcion().equals(descripcion)) {
                return tipo;
            }
        }
        return null;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorCliente;
    private javax.swing.JButton btnBuscarPorFechas;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnCrearReserva;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JComboBox<String> cmbTipoVehiculo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaReservas;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
