/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Gestion_Listas.ListaClientes;
import Gestion_Listas.ListaEmpleados;
import Gestion_Listas.ListaReservas;
import Gestion_Listas.ListaVehiculos;
import javax.swing.JInternalFrame;

/**
 *
 * @author Jeshuan
 */
public class Principal extends javax.swing.JFrame {
FrmBarraBotones barraBotones = new FrmBarraBotones(this);
FrmBarraInferior barraInferior = new FrmBarraInferior();

 private ListaVehiculos listaVehiculos;
 private ListaEmpleados listaEmpleados;
 private ListaReservas listaReservas;
 private ListaClientes listaClientes;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        listaClientes = new ListaClientes();
        listaEmpleados = new ListaEmpleados();
        listaVehiculos = new ListaVehiculos();
        listaReservas = new ListaReservas(listaClientes, listaVehiculos);
       DesktopPane.add(barraBotones);
     
       DesktopPane.add(barraInferior);
       barraBotones.setVisible(true);
    
       barraInferior.setVisible(true);
       barraBotones.setLocation(0, 0); 
       barraInferior.setLocation(310, 150); 
    }
    public void mostrarCliente(){
       FrmClientes Clientes = new FrmClientes(listaReservas,listaClientes);
       Clientes.setList(listaClientes);
       DesktopPane.add(Clientes);
        Clientes.setVisible(true);
       Clientes.setLocation(280, 100); 
    }
    public void mostrarEmpleado(){
       FrmEmpleados Empleados = new FrmEmpleados();
       Empleados.setList(listaEmpleados);
       DesktopPane.add(Empleados);
        Empleados.setVisible(true);
       Empleados.setLocation(280, 100); 
    }
    public void mostrarVehiculo(){
       InternalVehiculo Vehiculo = new InternalVehiculo();
       Vehiculo.setList(listaVehiculos);
       DesktopPane.add(Vehiculo);
        Vehiculo.setVisible(true);
       Vehiculo.setLocation(280, 100); 
    }
     public void mostrarReserva(){
       FrmReservas Reserva = new FrmReservas(listaReservas, listaClientes, listaVehiculos);
       Reserva.setList(listaReservas);
       DesktopPane.add(Reserva);
        Reserva.setVisible(true);
       Reserva.setLocation(280, 100); 
    }
    public void mostrarHome(){
    for (JInternalFrame frame : DesktopPane.getAllFrames()) {
        
        if (frame != barraInferior && frame != barraBotones) {
            frame.dispose();
           
        }
    } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        DesktopPane = new javax.swing.JDesktopPane();
        Label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N

        DesktopPane.setLayer(Label1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel Label1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
